faff: Update dependencies
Twilio breaks on Node v25+ because one of their indirect dependencies (buffer-equal-constant-time) uses a `SlowBuffer` mechanism that was removed from Node.js. The consuming package (jwa) released a patched version in May, which we can adopt by using an override.

> TypeError: Cannot read properties of undefined (reading 'prototype')
>> at Object.<anonymous> (node_modules/buffer-equal-constant-time/index.js:37:35)
>> at Object.<anonymous> (node_modules/jsonwebtoken/node_modules/jwa/index.js:1:19)
>> at Object.<anonymous> (node_modules/jsonwebtoken/node_modules/jws/lib/sign-stream.js:4:11)
>> at Object.<anonymous> (node_modules/jsonwebtoken/node_modules/jws/index.js:2:18)
>> at Object.<anonymous> (node_modules/jsonwebtoken/decode.js:1:11)
>> at Object.<anonymous> (node_modules/jsonwebtoken/index.js:2:11)
>> at Object.<anonymous> (node_modules/twilio/lib/jwt/validation/ValidationToken.js:6:40)
>> at Object.<anonymous> (node_modules/twilio/lib/base/RequestClient.js:45:43)
>> at Object.<anonymous> (node_modules/twilio/lib/base/BaseTwilio.js:5:41)
>> at Object.<anonymous> (node_modules/twilio/lib/rest/Twilio.js:12:22)
>> at Object.<anonymous> (node_modules/twilio/lib/index.js:38:34)